NodeOUs:
    Enable: true
    ClientOUIdentifier:
      Certificate: cacerts/ca-xuhaohh-xuhaohh-bsnbase-com-7054.pem
      OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
      Certificate: cacerts/ca-xuhaohh-xuhaohh-bsnbase-com-7054.pem
      OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
      Certificate: cacerts/ca-xuhaohh-xuhaohh-bsnbase-com-7054.pem
      OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
      Certificate: cacerts/ca-xuhaohh-xuhaohh-bsnbase-com-7054.pem
      OrganizationalUnitIdentifier: orderer
